<div id="forgot-container">
    <div class="container">
        <?php
        /**
         * @var Auth\Form\Signup $form
         */

        $form->prepare()
            ->setAttribute('action', $this->url('forgotPassword'));
        $email = $form->get('email');
        ?>
        <?=$this->form()->openTag($form); ?>
            <nav class="breadcrumbs">
                <ul>
                    <li><a href="<?=$this->url('auth') ?>" class="icon icon-home"></a></li>
                    <li><?=$this->translate('Forgot password') ?></li>
                </ul>
            </nav>

            <p><?=sprintf($this->translate('An email will be sent to your email address with instructions to reset your password. You may have to check your spams and authorize %s'), 'noreply@codetiburon.com'); ?></p>
            <div class="inputs">
                <?=$this->formInput($email); ?>
                <?=$this->formButton($form->get('submit')); ?>
            </div>
        <?=$this->form()->closeTag(); ?>
    </div>
</div>