<?php
/**
 * @var Auth\Form\RestorePassword $form
 */
$form->prepare()
    ->setAttribute('action', $this->url('restorePassword', ['hash' => $hash]));
$password = $form->get('password');
$cpassword = $form->get('cpassword');
?>

<div id="restore-container">
    <div class="container">
        <?php
        /**
         * @var Auth\Form\RestorePassword $form
         */
        $form->prepare()
            ->setAttribute('action', $this->url('restorePassword', ['hash' => $hash]));
        //->setAttribute('class', 'form-inline');
        $password = $form->get('password');
        $cpassword = $form->get('cpassword');
        ?>
        <?=$this->form()->openTag($form); ?>
            <nav class="breadcrumbs">
                <ul>
                    <li><a href="<?=$this->url('auth') ?>" class="icon icon-home"></a></li>
                    <li><?=$this->translate('Restore password') ?></li>
                </ul>
            </nav>

            <h2><?=$this->translate('Please, enter your new password'); ?></h2>

            <div class="inputs">
                <?=$this->formInput($password); ?>
                <?=$this->formInput($cpassword); ?>
                <?=$this->formButton($form->get('submit')); ?>
            </div>
        <?=$this->form()->closeTag(); ?>
    </div>
</div>