<?php echo $this->doctype() . PHP_EOL; ?>
<html lang="en">
    <head>
        <noscript>
            <meta http-equiv="Refresh" content="0;URL=/browser">
        </noscript>
    <?php
        $this->headMeta()
            ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
            ->appendHttpEquiv('Content-Language', 'en-US')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,chrome=1')
            ->setCharset('UTF-8')
            ->appendName('keywords', '')
            ->appendName('description', '')
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('baseurl', 'width=device-width, initial-scale=1.0')
            ;

        $this->headTitle('LINKAVIE.com' . $this->title)->setSeparator(' - ')->setAutoEscape(false);

        $this->headLink(array(
            'rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon',
            'href' => $this->basePath('/assets/linkavie/img/favicon.ico')
        ));

        $this->joinStylesheet('global');
        $this->joinStylesheet('main');
        $this->joinStylesheet('form');
        $this->joinStylesheet('auth/layout');
        $this->joinStylesheet('auth/auth-form');

        switch ($this->routeName)
        {
            case 'auth':
	            $this->joinStylesheet('auth/slider');
	        case 'newLanding':
	        case 'getLinkavie':
                $this->joinStylesheet('auth/auth-menu');
        }

        $this->headScript();

        echo (strlen($this->headMeta()) ? $this->headMeta()->toString(8).PHP_EOL : '');
        echo (strlen($this->headTitle()) ? $this->headTitle()->toString(8).PHP_EOL : '');
        echo (strlen($this->headLink()) ? $this->headLink()->toString(8).PHP_EOL : '');
        echo (strlen($this->headStyle()) ? $this->headStyle()->toString(8).PHP_EOL : '');
        echo (strlen($this->headScript()) ? $this->headScript()->toString(8).PHP_EOL : '');

    ?>
    </head>
    <body id="page-<?php echo strtolower(str_replace('/', '-', $this->routeName)); ?>">
        <?php if ($this->routeName == 'newLanding') { ?>
	        <header class="p-main">
		        <div class="container">
			        <div class="header-banner">
				        <a href="<?= $this->url('home'); ?>" class="banner">LINKAVIE</a>
			        </div>
		        </div>
	        </header>
        <?php } else { ?>
	        <header class="p-main">
	            <div class="container">
	                <a href="<?php echo $this->url('auth'); ?>" class="banner">LINKAVIE</a>
	            </div>
	        </header>
        <?php } ?>
        <div id="page">
            <?php echo $this->content; ?>
        </div>
        <footer>
            <div class="copyright">
                <div class="container">
                    <p>LINKAVIE 2013 &copy;, All rights reserved</p>
                </div>
            </div>
        </footer>

        <?php
        $fm = new Zend\Mvc\Controller\Plugin\FlashMessenger();
        $aMessages = array();

        foreach ($fm->getMessages() as $message) {
            $aMessages[] = array('group' => 'default', 'message' => $message);
        }

        foreach ($fm->getSuccessMessages() as $message) {
            $aMessages[] = array('group' => 'success', 'message' => $message);
        }

        foreach ($fm->getInfoMessages() as $message) {
            $aMessages[] = array('group' => 'info', 'message' => $message);
        }

        foreach ($fm->getErrorMessages() as $message) {
            $aMessages[] = array('group' => 'error', 'message' => $message);
        }

        // Setting inline scripts
        $this->inlineScript()
            ->prependFile($this->basePath('/assets/linkavie/js/main.js'))
            ->prependFile($this->basePath() . '/assets/linkavie/js/form.js')
        ;

        switch ($this->routeName)
        {
            case 'auth':
	        case 'newLanding':
	        case 'getLinkavie':
                $this->inlineScript()
	                ->prependFile($this->basePath('/assets/linkavie/js/auth/landing-menu.js'))
	                ->prependFile($this->basePath('/assets/lib/linkavie/linkavie.get-offset.js'));
        }

        $this->inlineScript()
            ->prependFile($this->basePath('/assets/lib/jquery.ui/1.10.3/jquery-ui.min.js'))
            ->prependFile($this->basePath('/assets/lib/modernizr/modernizr.js'))
            ->prependFile($this->basePath('/assets/lib/jquery/jquery.gritter.min.js'))
            ->prependFile($this->basePath('/assets/lib/jquery/jquery-1.8.3.min.js'))
            ->prependFile($this->basePath('/assets/lib/less/less-1.3.3.min.js'))
            ->prependFile($this->basePath('/assets/linkavie/js/fix-ie-placeholder.js'))
            ->appendFile($this->basePath('/assets/lib/linkavie/linkavie.translate.js'))
            ->appendFile($this->basePath('/assets/lib/linkavie/linkavie.ajax.js'))
        ;

        if ($this->inlineScript()->count()) echo $this->inlineScript()->toString(8), PHP_EOL;

        foreach ($aMessages as $key => $message) { //TODO: Remove HPOS
            if ($message['group'] == 'info') {
                unset($aMessages[$key]);
            }
        }
        ?>
        <script type="text/javascript">
            Global = Global ? Global : {} ;
            Global.messages = $.parseJSON('<?php echo json_encode($aMessages); ?>');
            Global.baseDomain = '<?php echo $this->host; ?>';
        </script>
    </body>
</html>