<?php
/**
 * @var \ $request
 * @var \ $restoreHash
 */
?>
<table class="mail_body"
       style="border-collapse: collapse; border-spacing: 0; padding: 0; margin: 0 auto; width: 520px;">
    <tbody>
    <tr>
        <td style="border-collapse: collapse; border-spacing: 0; padding: 0;">
            <h1 style="font-size: 28px; font-weight: bold; color: #333333; font-family: open_sansregular, Arial, serif; margin: 14px 0; text-align: left;">
                LINKAVIE</h1>

            <p style="font-size: 14px; color: #333333; font-family: open_sansregular, Arial, serif; margin: 14px 0; text-align: left;">
                Dear <?=$firstName;?></p>

            <p style="font-size: 14px; color: #333333; font-family: open_sansregular, Arial, serif; margin: 14px 0; text-align: left;">
                We have received a request to change or reset your LINKAVIE password.
                <br>If you are at the origin of this request, you can define a new
                password <a href="<?=$baseUrl . $this->url('restorePassword', ['hash' => $restoreHash]);?>">Here</a>.</p>

            <p style="font-size: 14px; color: #333333; font-family: open_sansregular, Arial, serif; margin: 14px 0; text-align: left;">
                If you don't want to change your password, just ignore this message.</p>

            <p style="font-size: 14px; color: #333333; font-family: open_sansregular, Arial, serif; margin: 14px 0; text-align: left;">
                Thanks!<br>
                The LINKAVIE team<br>
                <a href="mailto:contact@linkavie.com">contact@linkavie.com</a></p>
        </td>
    </tr>
    </tbody>
</table>
