<?php
$this->joinStylesheet('user/dashboard');
$this->joinStylesheet('userAvtarBlock');

$user = $this->currentUser();

$this->inlineScript()
    ->appendFile($this->basePath('/assets/linkavie/js/user/user.dashboard.js'))
?>

<div id="dashboard">
    <header>
        <div class="container">
            <div id="user-info">
                <div id="user-picture"><a href="#"><img src="<?php
                       echo $this->userAvatar($user->avatar, $user->id, '168x168'); ?>" alt=""/></a></div>
                <h2 id="user-name"><?php echo $user->first_name . ' ' . $user->last_name; ?></h2>
            </div>
        </div>
    </header>
    <div id="news">
        <div class="container">
            <div id="adverts">
                <a href="#"><img src="http://lorempixel.com/323/434/fashion/1" alt="Advert"/></a>
                <a href="#"><img src="http://lorempixel.com/323/434/sports/2" alt="Advert"/></a>
            </div>

            <div class="b-event-list">
                <div class="b-event-list__messages">
                    <?php if ($this->currentUser()->msg_howtostart) { ?>
                        <div class="b-event-list__item">
                            <div class="b-user-avatar-middle">
                                <a href="#" class="b-user-avatar-middle__link"><img src="<?php echo $this->basePath(
                                        '/assets/linkavie/img/linkavie-logo-100x100.jpg'
                                    ); ?>" alt="Thumbnail" class="b-user-avatar-middle__image"/></a>
                            </div>
                            <div class="content">
                                <h3><?php echo $this->translate('Welcome to LINKAVIE !....How to start?'); ?></h3>
                                <ul>
                                    <li><?php echo $this->translate('Complete your profile by adding your picture.') .
                                            sprintf(
                                                $this->translate('More info %shere%s'),
                                                '<a href="http://blog.linkavie.com/en/how-to-start/">',
                                                '</a>'
                                            ); ?></li>
                                    <li><?php echo $this->translate(
                                                'Store, organize and secure your pictures by uploading them to your personal Vault.'
                                            ) .
                                            sprintf(
                                                $this->translate('More info %shere%s'),
                                                '<a href="http://blog.linkavie.com/en/how-to-start/">',
                                                '</a>'
                                            ); ?></li>
                                    <li><?php echo $this->translate(
                                                'Start creating a rich Digital album and share it with friends.'
                                            ) .
                                            sprintf(
                                                $this->translate('More info %shere%s'),
                                                '<a href="http://blog.linkavie.com/en/how-to-start/">',
                                                '</a>'
                                            ); ?></a></li>
                                    <li><?php echo $this->translate(
                                                'Invite your friends to become LINKAVIE friends and share your emotions with them.'
                                            ) .
                                            sprintf(
                                                $this->translate('More info %shere%s'),
                                                '<a href="http://blog.linkavie.com/en/how-to-start/">',
                                                '</a>'
                                            ); ?></li>
                                    <li><?php echo $this->translate(
                                                'Share pictures or share a page, chapter or your entire Digital album with your friends.'
                                            ) .
                                            sprintf(
                                                $this->translate('More info %shere%s'),
                                                '<a href="http://blog.linkavie.com/en/how-to-start/">',
                                                '</a>'
                                            ); ?></li>
                                    <li><?php echo sprintf(
		                                    $this->translate('Visit our %sblog%s'),
		                                    '<a href="http://blog.linkavie.com/en/">',
		                                    '</a>'
	                                    ); ?></li>
                                </ul>
                                <p><?php echo $this->translate(
                                        'Enjoy the LINKAVIE experience, many more features are coming!'
                                    ); ?></p>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <div class="b-event-list__events"></div>
            </div>
        </div>
    </div>
</div>